version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./ChatAppWeb/Dockerfile 
    restart: unless-stopped
    mem_limit: 512M

  api: 
    image: chatAppAPI
    build:
        context: .
        dockerfile: ./ChatAppAPI/Dockerfile
    restart: unless-stopped
    ports: 
        - 5000:80


  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
 
  # swag:
  #   image: lscr.io/linuxserver/swag
  #   container_name: stratego
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Denver
  #     - URL=stratego2023.duckdns.org
  #     - VALIDATION=duckdns
  #     - DUCKDNSTOKEN=${DUCKDNSTOKEN}
  #     - STAGING=false
  #   volumes:
  #     - /home/stratego/data/swag:/config
  #     - ./swag-default.conf:/config/nginx/site-confs/default.conf # new part
  #   ports:
  #   - 0.0.0.0:2002:443 # note using port 443