receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  grafana-loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  prometheus:
    endpoint: "http://localhost:9090"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, grafana-loki]
