global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'your-app'
    static_configs:
      - targets: ['api:4002']

remote_write:
  - url: "http://loki:3100/loki/api/v1/push"
    basic_auth:
      username: 'admin'
      password: 'admin'